package com.example.backend.util.exception;

import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.ResponseStatus;

/**
 * Thrown when a user tries to access or modify a resource they don't own or aren't allowed to.
 */
@ResponseStatus(HttpStatus.UNAUTHORIZED)  // Sends 401 response automatically
public class UnauthorizedException extends RuntimeException {

    public UnauthorizedException() {
        super("Unauthorized access");
    }

    public UnauthorizedException(String message) {
        super(message);
    }
}

// Recommend and generated by ChatGPT
